import { Chord } from 'src/app/models/chord.model';

export const G_CHORDS: Chord[] = [
  {
    type: 'Major',
    fretStart: 0,
    fretEnd: 3,
    notes: [
      { fret: 3, string: 0 },
      { fret: 0, string: 1 },
      { fret: 0, string: 2 },
      { fret: 0, string: 3 },
      { fret: 2, string: 4 },
      { fret: 3, string: 5 },
    ],
    disabledStrings: [],
  },
  {
    type: 'Major',
    fretStart: 3,
    fretEnd: 6,
    notes: [
      { fret: 3, string: 0 },
      { fret: 3, string: 1 },
      { fret: 4, string: 2 },
      { fret: 5, string: 3 },
      { fret: 5, string: 4 },
      { fret: 3, string: 5 },
    ],
    disabledStrings: [],
    barre: { fret: 3, stringStart: 0, stringEnd: 5 },
  },
  {
    type: 'Major',
    fretStart: 5,
    fretEnd: 8,
    notes: [
      { fret: 7, string: 0 },
      { fret: 8, string: 1 },
      { fret: 7, string: 2 },
      { fret: 5, string: 3 },
    ],
    disabledStrings: [4, 5],
  },
  {
    type: 'Major',
    fretStart: 7,
    fretEnd: 10,
    notes: [
      { fret: 7, string: 0 },
      { fret: 8, string: 1 },
      { fret: 7, string: 2 },
      { fret: 9, string: 3 },
      { fret: 10, string: 4 },
    ],
    disabledStrings: [5],
    barre: { fret: 7, stringStart: 0, stringEnd: 2 },
  },
  {
    type: 'Major',
    fretStart: 10,
    fretEnd: 13,
    notes: [
      { fret: 10, string: 0 },
      { fret: 12, string: 1 },
      { fret: 12, string: 2 },
      { fret: 12, string: 3 },
      { fret: 10, string: 4 },
    ],
    disabledStrings: [5],
    barre: { fret: 10, stringStart: 0, stringEnd: 4 },
  },
  {
    type: 'Minor',
    fretStart: 3,
    fretEnd: 6,
    notes: [
      { fret: 3, string: 0 },
      { fret: 3, string: 1 },
      { fret: 3, string: 2 },
      { fret: 5, string: 3 },
      { fret: 5, string: 4 },
      { fret: 3, string: 5 },
    ],
    disabledStrings: [],
    barre: { fret: 3, stringStart: 0, stringEnd: 5 },
  },
  {
    type: 'Minor',
    fretStart: 5,
    fretEnd: 8,
    notes: [
      { fret: 6, string: 0 },
      { fret: 8, string: 1 },
      { fret: 7, string: 2 },
      { fret: 5, string: 3 },
    ],
    disabledStrings: [4, 5],
  },
  {
    type: 'Minor',
    fretStart: 10,
    fretEnd: 13,
    notes: [
      { fret: 10, string: 0 },
      { fret: 11, string: 1 },
      { fret: 12, string: 2 },
      { fret: 12, string: 3 },
      { fret: 10, string: 4 },
    ],
    disabledStrings: [5],
    barre: { fret: 10, stringEnd: 4, stringStart: 0 },
  },
  {
    type: '5',
    fretStart: 3,
    fretEnd: 6,
    notes: [
      { fret: 3, string: 5 },
      { fret: 5, string: 4 },
      { fret: 5, string: 3 },
    ],
    disabledStrings: [0, 1, 2],
  },
  {
    type: '5',
    fretStart: 3,
    fretEnd: 6,
    notes: [
      { fret: 3, string: 5 },
      { fret: 5, string: 4 },
    ],
    disabledStrings: [0, 1, 2, 3],
  },
  {
    type: '5',
    fretStart: 5,
    fretEnd: 8,
    notes: [
      { fret: 5, string: 3 },
      { fret: 7, string: 2 },
      { fret: 8, string: 1 },
    ],
    disabledStrings: [0, 4, 5],
  },
  {
    type: '5',
    fretStart: 5,
    fretEnd: 8,
    notes: [
      { fret: 5, string: 3 },
      { fret: 7, string: 2 },
      { fret: 8, string: 1 },
    ],
    disabledStrings: [0, 1, 4, 5],
  },
  {
    type: '5',
    fretStart: 10,
    fretEnd: 13,
    notes: [
      { fret: 10, string: 4 },
      { fret: 12, string: 3 },
      { fret: 12, string: 2 },
    ],
    disabledStrings: [0, 1, 5],
  },
  {
    type: '5',
    fretStart: 10,
    fretEnd: 13,
    notes: [
      { fret: 10, string: 4 },
      { fret: 12, string: 3 },
    ],
    disabledStrings: [0, 1, 2, 5],
  },
  {
    type: '7',
    fretStart: 3,
    fretEnd: 6,
    notes: [
      { fret: 3, string: 5 },
      { fret: 5, string: 4 },
      { fret: 3, string: 3 },
      { fret: 4, string: 2 },
      { fret: 3, string: 1 },
      { fret: 3, string: 0 },
    ],
    disabledStrings: [],
    barre: { fret: 3, stringStart: 0, stringEnd: 5 },
  },
  {
    type: '7',
    fretStart: 5,
    fretEnd: 8,
    notes: [
      { fret: 5, string: 3 },
      { fret: 7, string: 2 },
      { fret: 6, string: 1 },
      { fret: 7, string: 0 },
    ],
    disabledStrings: [4, 5],
  },
  {
    type: '7',
    fretStart: 8,
    fretEnd: 10,
    notes: [
      { fret: 10, string: 4 },
      { fret: 9, string: 3 },
      { fret: 10, string: 2 },
      { fret: 8, string: 1 },
    ],
    disabledStrings: [0, 5],
  },
  {
    type: '7',
    fretStart: 10,
    fretEnd: 13,
    notes: [
      { fret: 10, string: 4 },
      { fret: 12, string: 3 },
      { fret: 10, string: 2 },
      { fret: 12, string: 1 },
      { fret: 10, string: 0 },
    ],
    disabledStrings: [5],
    barre: { fret: 10, stringEnd: 4, stringStart: 0 },
  },
  {
    type: 'maj7',
    fretStart: 2,
    fretEnd: 5,
    notes: [
      { fret: 5, string: 3 },
      { fret: 4, string: 2 },
      { fret: 3, string: 1 },
      { fret: 2, string: 0 },
    ],
    disabledStrings: [4, 5],
  },
  {
    type: 'maj7',
    fretStart: 3,
    fretEnd: 6,
    notes: [
      { fret: 3, string: 5 },
      { fret: 5, string: 4 },
      { fret: 4, string: 3 },
      { fret: 4, string: 2 },
      { fret: 3, string: 1 },
      { fret: 3, string: 0 },
    ],
    disabledStrings: [0],
    barre: { fret: 3, stringStart: 0, stringEnd: 5 },
  },
  {
    type: 'maj7',
    fretStart: 3,
    fretEnd: 6,
    notes: [
      { fret: 3, string: 5 },
      { fret: 4, string: 3 },
      { fret: 4, string: 2 },
      { fret: 3, string: 1 },
    ],
    disabledStrings: [4, 0],
  },
  {
    type: 'maj7',
    fretStart: 5,
    fretEnd: 8,
    notes: [
      { fret: 5, string: 3 },
      { fret: 7, string: 2 },
      { fret: 7, string: 1 },
      { fret: 7, string: 0 },
    ],
    disabledStrings: [4, 5],
  },
  {
    type: 'maj7',
    fretStart: 7,
    fretEnd: 10,
    notes: [
      { fret: 10, string: 4 },
      { fret: 9, string: 3 },
      { fret: 7, string: 2 },
      { fret: 7, string: 1 },
      { fret: 7, string: 0 },
    ],
    disabledStrings: [5],
    barre: { fret: 7, stringEnd: 2, stringStart: 0 },
  },
  {
    type: 'maj7',
    fretStart: 10,
    fretEnd: 13,
    notes: [
      { fret: 10, string: 4 },
      { fret: 12, string: 3 },
      { fret: 11, string: 2 },
      { fret: 12, string: 1 },
      { fret: 10, string: 0 },
    ],
    disabledStrings: [5],
    barre: { fret: 10, stringEnd: 4, stringStart: 0 },
  },
  {
    type: 'm7',
    fretStart: 3,
    fretEnd: 6,
    notes: [
      { fret: 3, string: 5 },
      { fret: 5, string: 4 },
      { fret: 3, string: 3 },
      { fret: 3, string: 2 },
      { fret: 3, string: 1 },
      { fret: 3, string: 0 },
    ],
    disabledStrings: [],
    barre: { fret: 3, stringEnd: 5, stringStart: 0 },
  },
  {
    type: 'm7',
    fretStart: 5,
    fretEnd: 8,
    notes: [
      { fret: 5, string: 3 },
      { fret: 7, string: 2 },
      { fret: 6, string: 1 },
      { fret: 6, string: 0 },
    ],
    disabledStrings: [4, 5],
  },
  {
    type: 'm7',
    fretStart: 10,
    fretEnd: 13,
    notes: [
      { fret: 10, string: 4 },
      { fret: 12, string: 3 },
      { fret: 10, string: 2 },
      { fret: 11, string: 1 },
      { fret: 10, string: 0 },
    ],
    disabledStrings: [5],
    barre: { fret: 10, stringEnd: 4, stringStart: 0 },
  },
  {
    type: 'sus4',
    fretStart: 3,
    fretEnd: 6,
    notes: [
      { fret: 3, string: 5 },
      { fret: 5, string: 4 },
      { fret: 5, string: 3 },
      { fret: 5, string: 2 },
      { fret: 3, string: 1 },
      { fret: 3, string: 0 },
    ],
    disabledStrings: [],
    barre: { fret: 3, stringEnd: 5, stringStart: 0 },
  },
  {
    type: 'sus4',
    fretStart: 5,
    fretEnd: 8,
    notes: [
      { fret: 5, string: 3 },
      { fret: 7, string: 2 },
      { fret: 8, string: 1 },
      { fret: 8, string: 0 },
    ],
    disabledStrings: [4, 5],
  },
  {
    type: 'sus4',
    fretStart: 10,
    fretEnd: 13,
    notes: [
      { fret: 10, string: 4 },
      { fret: 12, string: 3 },
      { fret: 12, string: 2 },
      { fret: 13, string: 1 },
      { fret: 10, string: 0 },
    ],
    disabledStrings: [5],
    barre: { fret: 10, stringEnd: 4, stringStart: 0 },
  },
  {
    type: 'add9',
    fretStart: 3,
    fretEnd: 6,
    notes: [
      { fret: 5, string: 3 },
      { fret: 4, string: 2 },
      { fret: 3, string: 1 },
      { fret: 5, string: 0 },
    ],
    disabledStrings: [4, 5],
  },
  {
    type: 'sus2',
    fretStart: 5,
    fretEnd: 8,
    notes: [
      { fret: 5, string: 3 },
      { fret: 7, string: 2 },
      { fret: 8, string: 1 },
      { fret: 5, string: 0 },
    ],
    disabledStrings: [5, 4],
    barre: { fret: 5, stringEnd: 3, stringStart: 0 },
  },
  {
    type: 'sus2',
    fretStart: 10,
    fretEnd: 13,
    notes: [
      { fret: 10, string: 4 },
      { fret: 12, string: 3 },
      { fret: 12, string: 2 },
      { fret: 10, string: 1 },
      { fret: 10, string: 0 },
    ],
    disabledStrings: [5],
    barre: { fret: 10, stringEnd: 4, stringStart: 0 },
  },
  {
    type: '7sus4',
    fretStart: 3,
    fretEnd: 6,
    notes: [
      { fret: 3, string: 5 },
      { fret: 5, string: 4 },
      { fret: 3, string: 3 },
      { fret: 5, string: 2 },
      { fret: 3, string: 1 },
      { fret: 3, string: 0 },
    ],
    disabledStrings: [],
    barre: { fret: 3, stringEnd: 5, stringStart: 0 },
  },
  {
    type: '7sus4',
    fretStart: 5,
    fretEnd: 9,
    notes: [
      { fret: 5, string: 3 },
      { fret: 7, string: 2 },
      { fret: 6, string: 1 },
      { fret: 8, string: 0 },
    ],
    disabledStrings: [4, 5],
  },
  {
    type: '7sus4',
    fretStart: 10,
    fretEnd: 13,
    notes: [
      { fret: 10, string: 4 },
      { fret: 12, string: 3 },
      { fret: 10, string: 2 },
      { fret: 13, string: 1 },
      { fret: 10, string: 0 },
    ],
    disabledStrings: [5],
    barre: { fret: 10, stringEnd: 4, stringStart: 0 },
  },
  {
    type: '9',
    disabledStrings: [4, 5],
    fretStart: 4,
    fretEnd: 7,
    notes: [
      { fret: 5, string: 3 },
      { fret: 4, string: 2 },
      { fret: 6, string: 1 },
      { fret: 5, string: 0 },
    ],
  },
  {
    type: '9',
    disabledStrings: [0, 5],
    fretStart: 9,
    fretEnd: 11,
    notes: [
      { fret: 10, string: 4 },
      { fret: 9, string: 3 },
      { fret: 10, string: 2 },
      { fret: 10, string: 1 },
    ],
  },
  {
    type: '9',
    disabledStrings: [5],
    fretStart: 9,
    fretEnd: 11,
    notes: [
      { fret: 10, string: 4 },
      { fret: 9, string: 3 },
      { fret: 10, string: 2 },
      { fret: 10, string: 1 },
      { fret: 10, string: 0 },
    ],
    barre: { fret: 10, stringEnd: 2, stringStart: 0 },
  },
  {
    type: '7#9',
    disabledStrings: [4, 5],
    fretStart: 4,
    fretEnd: 7,
    notes: [
      { fret: 5, string: 3 },
      { fret: 4, string: 2 },
      { fret: 6, string: 1 },
      { fret: 6, string: 0 },
    ],
  },
  {
    type: '7#9',
    disabledStrings: [0, 5],
    fretStart: 9,
    fretEnd: 12,
    notes: [
      { fret: 10, string: 4 },
      { fret: 9, string: 3 },
      { fret: 10, string: 2 },
      { fret: 11, string: 1 },
    ],
  },
];
